# Site settings
title: Emphasis Parenthesis
tag_text: Emphasis Parenthesis
description: Emphasis Parenthesis. Building Better Software in a Better Way
baseurl: /emparsite


# Build settings
markdown: kramdown
include: [".htaccess"]
exclude: ["README.md", "config.ru"]
sass:
  style: compressed
